image: "rust:latest"

before_script:
        - export CARGO_HOME ="$CI_PROJECT_DIR/.cargo"

cache:
        paths:
                - .cargo
                - target

# Use cargo to test the project
test:cargo:
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --all --verbose
